/**
 * Created by Kashy.C on 10/22/18.
 */

export const LOGIN_ACTION = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT_ACTION = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const PROGRESS = "PROGRESS";

export const SIGNUP_ACTION = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const SET_TOKEN = "SET_TOKEN";
export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";

export const ACTION_REPOSITORIES_LIST = "ACTION_REPOSITORIES_LIST";
export const ACTION_LIST_ERROR = "ACTION_LIST_ERROR";
export const ACTION_LIST_SUCCESS = "ACTION_LIST_SUCCESS";

export const ACTION_README = "ACTION_README";
export const ACTION_README_SUCCESS = "ACTION_README_SUCCESS";
export const ACTION_README_ERROR = "ACTION_README_ERROR";
